version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "stable-develop"
    labels:
      - "stable"
    assignees:
      - "welles"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta-develop"
    labels:
      - "beta"
    assignees:
      - "welles"
